import "./src/styles/components/loader.scss"
import "./src/styles/components/text-info.scss"
import "./src/styles/layout/layout.scss"
import "./src/styles/layout/reset.scss"
import "./src/styles/layout/footer.scss"
import "./src/styles/pages/index.scss"