name: o2vie-chatel.ch deploy

on:
  release:
    types: [published]

jobs:
  deploy:
    if:  ${{ startsWith(github.event.release.tag_name, 'o2vie-') }}
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./o2vie-chatel.ch

    steps:
    - uses: actions/checkout@v2
      
    - uses: actions/setup-node@v2
      with:
        node-version: 15
    
    - name: Install dependencies
      run: |
        npm install
        npm install -g gatsby-cli
        
    - name: Build
      run: |
        echo "DIRECTUS_O2VIE_TOKEN=${{secrets.O2VIE_CH_DIRECTUS_O2VIE_TOKEN}}" >> .env.production
        gatsby build

    - name: Get the version
      id: version_file
      # output "o2vie-v1_2_3"
      run: echo ::set-output name=VERSION::$(echo ${GITHUB_REF/refs\/tags\//} | tr . _)

    - name: Create tar.gz
      run: |
        tar -czvf ${{ steps.version_file.outputs.VERSION }}.tar.gz public

    - name: Release
      id: release_pub
      # at this time of writing, the latest version does not contain the assets
      # output
      uses: softprops/action-gh-release@cd28b0f5ee8571b76cfdaa62a30d51d752317477
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: o2vie-chatel.ch/o2vie-*.tar.gz

    - name: Display output
      run: |
        echo "${{ steps.release_pub.outputs.assets }}"
        echo "${{ steps.release_pub.outputs.url }}"
        echo "${{ steps.release_pub.outputs.id }}"
        echo "${{ steps.release_pub.outputs.upload_url }}"
        echo "${{ steps.release_pub.outputs }}"

    - name: Trigger deploy
      run: |
        echo "${{ steps.release_pub.outputs.assets }}"
        curl -X POST -d "{\"browser_download_url\": \"${{ fromJSON(steps.release_pub.outputs.assets)[0].browser_download_url }}\"}" https://hodor.doxatech.ch/api/hook/o2vie

