name: bullenetwork.ch deploy

on:
  push:
    branches: [ production-bullenetwork-ch ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - uses: actions/setup-node@v1
      with:
        node-version: 13.8
    
    - name: Install dependencies
      run: |
        cd bullenetwork.ch
        npm install
        npm install -g gatsby-cli
        
    - name: Build
      run: |
        cd bullenetwork.ch
        gatsby build
        
    - name: Sync
      env:
        dest: 'eebulle@${{secrets.DEPLOY_ADDR}}:/var/www/bullenetwork.ch/public_html/'
      run: |
        echo "${{secrets.DEPLOY_BULLENETWORK_CH_KEY}}" > deploy_key
        chmod 600 ./deploy_key
        rsync -chav --delete \
          -e 'ssh -p ${{secrets.DEPLOY_PORT}} -i ./deploy_key -o StrictHostKeyChecking=no' \
          ./bullenetwork.ch/public/ ${{env.dest}}
