name: o2vie-chatel.ch deploy

on:
  workflow_dispatch:
  push:
    branches: [ production-o2vie-chatel-ch ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - uses: actions/setup-node@v2
      with:
        node-version: 15
    
    - name: Install dependencies
      run: |
        cd o2vie-chatel.ch
        npm install
        npm install -g gatsby-cli
        
    - name: Build
      run: |
        cd o2vie-chatel.ch
        echo "DIRECTUS_O2VIE_TOKEN=${{secrets.O2VIE_CH_DIRECTUS_O2VIE_TOKEN}}" >> .env.production
        gatsby build
        
    - name: Sync
      env:
        dest: 'eebulle@${{secrets.DEPLOY_ADDR}}:/var/www/o2vie-chatel.ch/public_html/'
      run: |
        echo "${{secrets.DEPLOY_O2VIE_CHATEL_CH_KEY}}" > deploy_key
        chmod 600 ./deploy_key
        rsync -chav --delete \
          -e 'ssh -p ${{secrets.DEPLOY_PORT}} -i ./deploy_key -o StrictHostKeyChecking=no' \
          ./o2vie-chatel.ch/public/ ${{env.dest}}
