name: bullenetwork.ch deploy

on:
  release:
    types: [published]

jobs:
  deploy:
    if:  ${{ startsWith(github.event.release.tag_name, 'bullenetwork-') }}
    runs-on: ubuntu-latest

  env:
    base_folder: bullenetwork.ch
    hodor_url: https://hodor.doxatech.ch
    hodor_key: bullenetwork

    defaults:
      run:
        working-directory: ./${{ env.base_folder }}

    steps:
    - uses: actions/checkout@v2
      
    - uses: actions/setup-node@v2
      with:
        node-version: 15
    
    - name: Install dependencies
      run: |
        npm install
        npm install -g gatsby-cli@2.8.29
        
    - name: Build
      env:
        GCS_PROXY_PARTITION: ${{secrets.BULLENETWORK_CH_GCS_PROXY_PARTITION}}
        GCS_PROXY_PARTITION_ARCHIVE: ${{secrets.BULLENETWORK_CH_GCS_PROXY_PARTITION_ARCHIVE}}
        GCS_PROXY_MEDIAS: ${{secrets.BULLENETWORK_CH_GCS_PROXY_MEDIAS}}
        GCS_PROXY_MEDIAS_ARCHIVE: ${{secrets.BULLENETWORK_CH_GCS_PROXY_MEDIAS_ARCHIVE}}
        DIRECTUS_ADMIN_TOKEN: ${{secrets.BULLENETWORK_CH_DIRECTUS_ADMIN_TOKEN}}
      run: gatsby build

    - name: Get the version
      id: version_file
      # output "bullenetwork-v1_2_3"
      run: echo ::set-output name=VERSION::$(echo ${GITHUB_REF/refs\/tags\//} | tr . _)

    - name: Create tar.gz
      run: |
        tar -czvf ${{ steps.version_file.outputs.VERSION }}.tar.gz public

    - name: Release
      id: release_pub
      # at this time of writing, the latest version does not contain the assets
      # output
      uses: softprops/action-gh-release@cd28b0f5ee8571b76cfdaa62a30d51d752317477
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ env.base_folder }}/${{ steps.version_file.outputs.VERSION }}.tar.gz

    - name: Trigger deploy
      run: |
        curl -X POST -d "{\"browser_download_url\": \"${{ fromJSON(steps.release_pub.outputs.assets)[0].browser_download_url }}\"}" ${{ env.hodor_url }}/api/hook/${{ env.hodor_key }}

