name: o2vie-chatel.ch deploy

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./o2vie-chatel.ch

    steps:
    - uses: actions/checkout@v2
      
    - uses: actions/setup-node@v2
      with:
        node-version: 15
    
    - name: Install dependencies
      run: |
        npm install
        npm install -g gatsby-cli
        
    - name: Build
      run: |
        echo "DIRECTUS_O2VIE_TOKEN=${{secrets.O2VIE_CH_DIRECTUS_O2VIE_TOKEN}}" >> .env.production
        gatsby build

    - name: Get the version
      id: get_version
      # output "v1_2_3"
      run: echo ::set-output name=VERSION::$(echo ${GITHUB_REF/refs\/tags\//} | tr . _)

    - name: Create tar.gz
      run: |
        tar -czvf o2vie_${{ steps.get_version.outputs.VERSION }}.tar.gz public

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: o2vie_*.tar.gz
      id: release

    - name: Trigger deploy
      run: |
        echo "Release to be published: ${{ fromJSON(steps.release.outputs.assets)[0].browser_download_url }}"
        curl -X POST -d "{\"browser_download_url\": \"${{ fromJSON(steps.release.outputs.assets)[0].browser_download_url }}\"} https://hodor.doxatech.ch/api/hook/o2vie

