name: bullenetwork.ch deploy

on:
  workflow_dispatch:
  push:
    branches: [ production-bullenetwork-ch ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - uses: actions/setup-node@v2
      with:
        node-version: 15
    
    - name: Install dependencies
      run: |
        cd bullenetwork.ch
        npm install
        npm install -g gatsby-cli@2.8.29
        
    - name: Build
      run: |
        cd bullenetwork.ch
        echo "GCS_PROXY_PARTITION=${{secrets.BULLENETWORK_CH_GCS_PROXY_PARTITION}}" >> .env.production
        echo "GCS_PROXY_PARTITION_ARCHIVE=${{secrets.BULLENETWORK_CH_GCS_PROXY_PARTITION_ARCHIVE}}" >> .env.production
        echo "GCS_PROXY_MEDIAS=${{secrets.BULLENETWORK_CH_GCS_PROXY_MEDIAS}}" >> .env.production
        echo "GCS_PROXY_MEDIAS_ARCHIVE=${{secrets.BULLENETWORK_CH_GCS_PROXY_MEDIAS_ARCHIVE}}" >> .env.production
        echo "DIRECTUS_ADMIN_TOKEN=${{secrets.BULLENETWORK_CH_DIRECTUS_ADMIN_TOKEN}}" >> .env.production
        gatsby build
        
    - name: Sync
      env:
        dest: 'eebulle@${{secrets.DEPLOY_ADDR}}:/var/www/bullenetwork.ch/public_html/'
      run: |
        echo "${{secrets.DEPLOY_BULLENETWORK_CH_KEY}}" > deploy_key
        chmod 600 ./deploy_key
        rsync -chav --delete \
          -e 'ssh -p ${{secrets.DEPLOY_PORT}} -i ./deploy_key -o StrictHostKeyChecking=no' \
          ./bullenetwork.ch/public/ ${{env.dest}}
